### ISSUE TITLE
build and release libbls384_256.a for ios/iossimulator

### ISSUE THREAD

**Issue by cnlangzi** [herumi/bls-go-binary#11]
Could you build binaries(libbls384_256.a) for ios/iossimulator, and include them on bls/lib/ios and bls/lib/iossimulator in new release?  
Because there are only 3 binaries for linux/windows/darwin on git repo now. We have to build it again if it is imported on building. if not, it throws `file not found` issue on gomobile building.

**Comment by herumi** [comment]
I don't push it because the file is large. May I push it with git-lfs?
