### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by ccorcoveanu** [herumi/bls-go-binary#12]
Hey! I was wondering why aren't you using semantic versioning for release tags, and if you could add a semantic release for the latest version. I am able to import the lib with pseudo-versions, but it would be a lot cleaner if i could just specify `v1.28.0`. Thanks a lot!

**Comment by herumi** [comment]
Okay, I'll use it from the next version. Is it okay to use v1.28.0 instead of v1.28?
