### ISSUE TITLE
build fail :/usr/bin/ld: cannot find -lstdc++

### ISSUE THREAD

**Issue by raojianli** [herumi/bls-go-binary#15]
go version 1.8; compile enviroment: docker centos7

`
 github.com/herumi/bls-go-binary/bls
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit statu

`

then I  run   yum install gcc-c++
a error

`
# github.com/herumi/bls-go-binary/bls
/opt/go/pkg/mod/github.com/herumi/bls-go-binary@v0.0.0-20200324054641-17de9ae04665/bls/lib/linux/amd64/libbls384_256.a(fp.o): In function `std::tr1::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_allocate_node(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> const&)':
fp.cpp:(.text._ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_N5Xbyak12LabelManager9SlabelValEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb1EE16_M_allocate_nodeERKSC_[_ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_N5Xbyak12LabelManager9SlabelValEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb1EE16_M_allocate_nodeERKSC_]+0x43): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/opt/go/pkg/

`

**Comment by herumi** [comment]
Sorry for the late response. How about `yum install libstdc++`?
