### ISSUE TITLE
Using semver for tags

### ISSUE THREAD

**Issue by AdoAdoAdo** [herumi/bls-go-binary#16]
Currently referencing tag `v1.29` does not work in go.mod as it does not follow semantic versioning `MAJOR.MINOR.PATCH`

Is it possible to create a tag that has also the PATCH version (e.g 1.29.0) ?

**Comment by herumi** [comment]
Okay, I've tagged it.

**Comment by herumi** [comment]
May the tag name not `1.29.0` but`v1.29.0`?

**Comment by cnlangzi** [comment]
> May the tag name not `1.29.0` but`v1.29.0`?

yes, all module should be versioned with vX.Y.Z. but please create release instead of creating tag. release works properly with `go get ...`

**Comment by AdoAdoAdo** [comment]
> May the tag name not `1.29.0` but`v1.29.0`?
Yes indeed, should be v1.29.0
:pray:

**Comment by herumi** [comment]
Okay, I used it.
