### ISSUE TITLE
latest libbls384_256 doesn't work on linux

### ISSUE THREAD

**Issue by cnlangzi** [herumi/bls-go-binary#19]
# command-line-arguments
/root/docker-build-actions-runner/_work/_tool/go/1.20.0/x64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /root/go/pkg/mod/github.com/cnlangzi/bls-go-binary@v1.29.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `std::tr1::_Hashtable<int, std::pair<int const, Xbyak::JmpLabel const>, std::allocator<std::pair<int const, Xbyak::JmpLabel const> >, std::_Select1st<std::pair<int const, Xbyak::JmpLabel const> >, std::equal_to<int>, std::tr1::hash<int>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, false>::_M_insert(std::pair<int const, Xbyak::JmpLabel const> const&, std::tr1::integral_constant<bool, false>) [clone .isra.0]':
fp.cpp:(.text+0x217b): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/go/pkg/mod/github.com/cnlangzi/bls-go-binary@v1.29.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `mcl::fp::Op::createFpGenerator()':
fp.cpp:(.text+0xd7fb): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/go/pkg/mod/github.com/cnlangzi/bls-go-binary@v1.29.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `std::tr1::_Hashtable<unsigned long, std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation>, std::allocator<std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation> >, std::_Select1st<std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation> >, std::equal_to<unsigned long>, std::tr1::hash<unsigned long>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_insert_bucket(std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation> const&, unsigned long, unsigned long)':
fp.cpp:(.text._ZNSt3tr110_HashtableImSt4pairIKmN5Xbyak13MmapAllocator10AllocationEESaIS6_ESt10_Select1stIS6_ESt8equal_toImENS_4hashImEENS_8__detail18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyELb0ELb0ELb1EE16_M_insert_bucketERKS6_mm[_ZNSt3tr110_HashtableImSt4pairIKmN5Xbyak13MmapAllocator10AllocationEESaIS6_ESt10_Select1stIS6_ESt8equal_toImENS_4hashImEENS_8__detail18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyELb0ELb0ELb1EE16_M_insert_bucketERKS6_mm]+0x3d1): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/go/pkg/mod/github.com/cnlangzi/bls-go-binary@v1.29.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `std::tr1::_Hashtable<int, std::pair<int const, Xbyak::LabelManager::ClabelVal>, std::allocator<std::pair<int const, Xbyak::LabelManager::ClabelVal> >, std::_Select1st<std::pair<int const, Xbyak::LabelManager::ClabelVal> >, std::equal_to<int>, std::tr1::hash<int>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_insert_bucket(std::pair<int const, Xbyak::LabelManager::ClabelVal> const&, unsigned long, unsigned long)':
fp.cpp:(.text._ZNSt3tr110_HashtableIiSt4pairIKiN5Xbyak12LabelManager9ClabelValEESaIS6_ESt10_Select1stIS6_ESt8equal_toIiENS_4hashIiEENS_8__detail18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyELb0ELb0ELb1EE16_M_insert_bucketERKS6_mm[_ZNSt3tr110_HashtableIiSt4pairIKiN5Xbyak12LabelManager9ClabelValEESaIS6_ESt10_Select1stIS6_ESt8equal_toIiENS_4hashIiEENS_8__detail18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyELb0ELb0ELb1EE16_M_insert_bucketERKS6_mm]+0x3f1): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/go/pkg/mod/github.com/cnlangzi/bls-go-binary@v1.29.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `Xbyak::LabelManager::defineClabel(Xbyak::Label&)':
fp.cpp:(.text._ZN5Xbyak12LabelManager12defineClabelERNS_5LabelE[_ZN5Xbyak12LabelManager12defineClabelERNS_5LabelE]+0x4f8): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/go/pkg/mod/github.com/cnlangzi/bls-go-binary@v1.29.0/bls/lib/linux/amd64/libbls384_256.a(fp.o):fp.cpp:(.text._ZN5Xbyak12LabelManager5resetEv[_ZN5Xbyak12LabelManager5resetEv]+0xe1f): more undefined references to `std::__throw_bad_array_new_length()' follow
collect2: error: ld returned 1 exit status

**Comment by herumi** [comment]
Could you use g++-10 instead of g++-11?
https://www.google.com/search?client=firefox-b-d&q=std%3A%3A__throw_bad_array_new_length%28%29+

**Comment by cnlangzi** [comment]
> Could you use g++-10 instead of g++-11? https://www.google.com/search?client=firefox-b-d&q=std%3A%3A__throw_bad_array_new_length%28%29+

it worked in previous release. let me try g++-10 as you suggested. 

refs
- https://bugs.launchpad.net/votca/+bug/1956898
- https://github.com/votca/votca/issues/941#issuecomment-1012829439

```
@jwakely That was very useful! Adding -Wl,--trace-symbol=_ZSt28__throw_bad_array_new_lengthv to the libvotca_xtp.so link lines shows:

/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libecpint.a(ecp.cpp.o): reference to _ZSt28__throw_bad_array_new_lengthv
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libecpint.a(ecpint.cpp.o): reference to _ZSt28__throw_bad_array_new_lengthv
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libecpint.a(gaussquad.cpp.o): reference to _ZSt28__throw_bad_array_new_lengthv
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libecpint.a(angular.cpp.o): reference to _ZSt28__throw_bad_array_new_lengthv
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libecpint.a(bessel.cpp.o): reference to _ZSt28__throw_bad_array_new_lengthv
So the problem is actually in the libecpint package, we get from Debian.
```

**Comment by cnlangzi** [comment]
try to build it with gcc-10 and clang++-15 on ubuntu. but it doesn't work
```
lz@lz-Ubuntu:~/code/github.com/cnlangzi/bls-go-binary$ clang -v
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
lz@lz-Ubuntu:~/code/github.com/cnlangzi/bls-go-binary$ make CXX=clang
make -f src//bls/Makefile.onelib BLS_DIR=src//bls MCL_DIR=src//bls/mcl OUT_DIR=/home/lz/code/github.com/cnlangzi/bls-go-binary ETH_CFLAGS= all
make[1]: Entering directory '/home/lz/code/github.com/cnlangzi/bls-go-binary'
clang -c src//bls/src/bls_c384_256.cpp -o obj/bls_c384_256.o -O3 -fno-exceptions -fno-threadsafe-statics -fno-rtti -fno-stack-protector -DNDEBUG -DMCL_DONT_USE_OPENSSL -DMCL_SIZEOF_UNIT=8 -DMCL_MAX_BIT_SIZE=384 -DCYBOZU_DONT_USE_EXCEPTION -DCYBOZU_DONT_USE_STRING -D_FORTIFY_SOURCE=0 -Isrc//bls/include -Isrc//bls/mcl/include   -std=c++03 -fpic -DMCL_USE_LLVM=1
clang -c src//bls/mcl/src/fp.cpp -o obj/fp.o -O3 -fno-exceptions -fno-threadsafe-statics -fno-rtti -fno-stack-protector -DNDEBUG -DMCL_DONT_USE_OPENSSL -DMCL_SIZEOF_UNIT=8 -DMCL_MAX_BIT_SIZE=384 -DCYBOZU_DONT_USE_EXCEPTION -DCYBOZU_DONT_USE_STRING -D_FORTIFY_SOURCE=0 -Isrc//bls/include -Isrc//bls/mcl/include   -std=c++03 -fpic -DMCL_USE_LLVM=1
In file included from src//bls/mcl/src/fp.cpp:4:
In file included from src//bls/mcl/include/mcl/op.hpp:9:
In file included from src//bls/mcl/include/mcl/gmp_util.hpp:17:
In file included from src//bls/mcl/include/mcl/randgen.hpp:33:
src//bls/mcl/include/cybozu/random_generator.hpp:133:19: warning: using directive refers to implicitly-defined namespace 'std'
                using namespace std;
                                ^
In file included from src//bls/mcl/src/fp.cpp:19:
In file included from src//bls/mcl/src/xbyak/xbyak_util.h:20:
src//bls/mcl/src/xbyak/xbyak.h:18:10: fatal error: 'list' file not found
#include <list>
         ^~~~~~
1 warning and 1 error generated.
make[1]: *** [src//bls/Makefile.onelib:77: obj/fp.o] Error 1
make[1]: Leaving directory '/home/lz/code/github.com/cnlangzi/bls-go-binary'
make: *** [Makefile:6: all] Error 2
lz@lz-Ubuntu:~/code/github.com/cnlangzi/bls-go-binary$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.3.0-1ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-S4I5Pr/gcc-10-10.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-S4I5Pr/gcc-10-10.3.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1~20.04) 

```

**Comment by cnlangzi** [comment]
@herumi  tried build it with gcc 9, it still throws `__throw_bad_array_new_length`.

**Comment by herumi** [comment]
It's due to old Ubuntu not having __throw_bad_array_new_length.
It occurs when running a library built with the new gcc on an old Ubuntu.
Would you be able to build with gcc-8?

**Comment by cnlangzi** [comment]
fixed it by upgrading ubuntu.

**Comment by cnlangzi** [comment]
it happens everywhere now. alpine, debain, windows ... . 
@herumi  do you think it is possible to downgrade it?   it worked everything as default installation in previous release.
![image](https://github.com/herumi/bls-go-binary/assets/347651/921b96fc-043a-4388-aea3-14dd06c1fd89)

**Comment by cnlangzi** [comment]
is it an option to compile it with `-static-libstdc++`
https://stackoverflow.com/a/73970018

**Comment by herumi** [comment]
Thank you for the information. I'll check it later.

**Comment by cnlangzi** [comment]
throw error on alpine 

```
40.31 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libOpenEXR-3_1.so.30: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
#0 40.31 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libOpenEXR-3_1.so.30: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
#0 40.31 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libIlmThread-3_1.so.30: undefined reference to `std::thread::_State::~_State()'
#0 40.31 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libOpenEXR-3_1.so.30: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)'
#0 40.31 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libOpenEXR-3_1.so.30: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
#0 40.31 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libOpenEXR-3_1.so.30: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const'
#0 40.31 collect2: error: ld returned 1 exit status
------
```

**Comment by cnlangzi** [comment]
@herumi  it has to install package from edge instead of stable on alpine.

```
RUN apk upgrade
RUN apk del libstdc++ gmp-dev openssl-dev vips-dev 
RUN apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main libstdc++ gmp-dev openssl-dev vips-dev 
```

**Comment by herumi** [comment]
bls/Makefile.onelib
```diff
 MIN_CFLAGS+=-std=c++03
+MIN_CFLAGS+=-static-libstdc++ -static-libgcc
```
I've tried the option, but it does not affect libbls384_256.a.

**Comment by cnlangzi** [comment]
@herumi  I tried to install msys2 on windows 10 pro. it shows some errors that I can't find solution in google.

install msys2 : https://github.com/msys2/msys2-installer/releases/download/2023-05-26/msys2-x86_64-20230526.exe
install packages:  `pacman -S base-devel git gcc make`  in `MSYS2 MINGW64` shell


```
# command-line-arguments
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-msys/11.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex: No such
 file or directory
/usr/lib/gcc/x86_64-pc-msys/11.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32: No such
 file or directory
collect2: error: ld returned 1 exit status

make: *** [Makefile:32: zbox] Error 2

cnlan@x260 MINGW64 /d/geax/github.com/0chain/zboxcli
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/11.3.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /c/S/gcc/src/gcc-11.3.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.3.0 (GCC)
```

**Comment by cnlangzi** [comment]
nvm, fixed it by `pacman -S  mingw-w64-x86_64-clang`

**Comment by cnlangzi** [comment]
@herumi  get both of them fixed. thanks.
