### ISSUE TITLE
arm libs are not compiled on release.yml because all runners are running on x86/64

### ISSUE THREAD

**Issue by cnlangzi** [herumi/bls-go-binary#24]
https://github.com/actions/runner-images

linux/arm64 can be complied in docker via `docker buildx`.  but it doesn't not work on m1 Mac. so we have to compile it manually for m1 mac.

**Comment by herumi** [comment]
I'll try the '-target' option later.
https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by herumi** [comment]
[The latest dev branch](https://github.com/herumi/bls/tree/dev) supports `make ARCH=x86_64` and `make ARCH=arm64` on macOS to build bls/lib/darwin/{amd64,arm64}/libbls384_256.a .
Don't forget to make clean before building the other architecture.

**Comment by herumi** [comment]
I modified Makefile to build M1 mac binary. https://github.com/herumi/bls-go-binary/issues/24#issuecomment-1575898452
Does this help?
