### ISSUE TITLE
how to solove?

### ISSUE THREAD

**Issue by juufuu** [herumi/bls-go-binary#25]
# awesomeProject3
D:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
D:/minG/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lbls384_256
collect2.exe: error: ld returned 1 exit status

**Comment by cnlangzi** [comment]
@juufuu  use latest release to build it
