### ISSUE TITLE
don't use `v2.*.*` to release it

### ISSUE THREAD

**Issue by cnlangzi** [herumi/bls-go-binary#28]
`v2` is very different from `v1`.  please don't use `v2` if it is unnecessary.

https://go.dev/blog/v2-go-modules

**Comment by herumi** [comment]
I can change to v1.40.0, but can I delete v2?

**Comment by cnlangzi** [comment]
Yes. in my opinion, it is safe to delete it. because it doesn't work with go mod. so there should be nobody to import it now.

**Comment by herumi** [comment]
Okay.

**Comment by herumi** [comment]
I released https://github.com/herumi/bls-go-binary/releases/tag/v1.31.0 .
