### ISSUE TITLE
Unable to use library in IOS

### ISSUE THREAD

**Issue by moldis** [herumi/bls-go-binary#7]
![image](https://user-images.githubusercontent.com/2959408/156492666-2eb09481-9a00-4415-bd36-9e2651aadef3.png)

**Comment by herumi** [comment]
Please make a library at yourself. see https://github.com/herumi/bls-go-binary#how-to-build-the-static-binary

```
make ios
```

**Comment by moldis** [comment]
I am using it differently. From my go library, I reference bls-go-binary package. them I am trying to build with `gomobile -target:ios `

building with `make ios` just giving me binary without header file, so I can't use it anyway without go code

**Comment by herumi** [comment]
>building with make ios just giving me binary without header file, so I can't use it anyway without go code

Header files for cgo to use this library are in `bls/include`. What message shows by `make ios`?

**Comment by moldis** [comment]
Header file - I mean `IOS/Mac bridge header`, without it, generated `.a` is useless and can't be used in IOS/Mac. 
As I said `make ios` I am able to generate binary, but if I import bls-go-binary package into `go code` and then build library with `gomobile target -ios` I am getting the error above.

**Comment by herumi** [comment]
What CPU, OS, and Xcode do you use?
And could you show me the Go code?
I don't know xcframewok, is there configuration to search libbls384_256.a?

**Comment by cnlangzi** [comment]
@herumi it says 
ld: in /Users/geax/code/geax/github.com/herumi/bls-go-binary/bls/lib/ios/libbls384_256.a(bls_c384_256.o), building for iOS Simulator, but linking in object file (/Users/geax/code/geax/github.com/herumi/bls-go-binary/bls/lib/ios/libbls384_256.a(bls_c384_256.o)) built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cnlangzi** [comment]
@herumi  fixed the build issue on https://github.com/herumi/bls-go-binary/pull/8
